basic/urls.py
from django.urls import path
from . import views

app_name = 'basic'

urlpatterns = [
    path('register', views.register, name='register'),
    path('user_login',views.user_login,name='user_login'),
    path('logout', views.user_logout, name='logout'),
    path('display1', views.Display1.as_view(), name='display1'),
    path('uploadpropic/<int:pk>', views.UserProfileInfoUpdate.as_view(), name='uploadpropic'),
    path('confirm_deletion/<int:pk>', views.UserDeleteConfirmationView.as_view(), name='confirm_deletion'),
    path('delete/<int:pk>', views.UserDeleteView.as_view(), name='delete'),
    path('member_list', views.member_list, name='member_list'),
    path('my_profile', views.my_profile, name='my_profile'),
    path('view_profile<str:user>', views.view_profile, name='view_profile'),
    path('userupdate/<int:id>', views.update_user, name='userupdate'),
    path('edit_user/<int:id>', views.edit_user, name='edit_user'),
    path('post_topic_list', views.PostTopicListView.as_view(), name='post_topic_list'),
    path('post_detail_view/<str:pt>', views.post_detail, name='post_detail_view'),
    path('post_create/<str:id>', views.PostCreateView.as_view(), name='post_create'),
    path('post_comment_no/<int:id>', views.post_comment_no, name='post_comment_no'),
    path('comment_view/<int:id>', views.comment_view, name='comment_view'),
    path('reply_view/<int:id>', views.reply_view, name='reply_view'),
    path('comment_create_view/<int:id>', views.CommentCreateView.as_view(), name='comment_create_view'),
    path('reply_create_view/<int:id>', views.ReplyCreateView.as_view(), name='reply_create_view'),
    path('like_post', views.like_post, name='like_post'),
    path('dislike_post', views.dislike_post, name='dislike_post'),
    path('like_comment', views.like_comment, name='like_comment'),
    path('dislike_comment', views.dislike_comment, name='dislike_comment'),
    path('confirm_post_deletion_view/<int:id>', views.confirm_to_delete_post, name='confirm_post_deletion_view'),
    path('confirm_comment_deletion_view/<int:id>', views.confirm_to_delete_comment, name='confirm_comment_deletion_view'),
    path('confirm_reply_deletion_view/<int:id>', views.confirm_to_delete_reply, name='confirm_reply_deletion_view'),
    path('delete_post/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    path('delete_comment/<int:pk>', views.CommentDeleteView.as_view(), name='delete_comment'),
    path('procedure', views.ProcedureView.as_view(), name='procedure'),
]

pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from basic import views as basic_views

admin.site.site_header = "MY ADMIN"
admin.site.site_title = "My Admin"

urlpatterns = [
    path('', basic_views.HomeView.as_view(), name='home'),
    path('panto/', admin.site.urls),
    path('basic/', include ('basic.urls', namespace='basic')),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password-reset-done', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>OUR BLOGGING SITE</title>
    <link rel="stylesheet" href="{% static 'mycss/style.css' %}"/>
</head>
<nav class="navbar navbar-dark bg-dark">
    <ul class="nav justify-content-left">
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link my-color" href="{% url 'basic:procedure' %}">Procedure</a>
        </li>
        {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">Members</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">To Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">My Profile</a>
            </li>
        {% else %}
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:post_topic_list' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:member_list' %}">Members</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:post_create' id=user %}">To Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:my_profile' %}">My Profile</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">Members</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">To Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">My Profile</a>
                </li>
            {% endif %}
        {% endif %}
    </ul>
    <ul class="nav justify-content-right">
        {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:register' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-j</title><path style="fill:cornsilk;" d="M256,48C141.31,48,48,141.31,48,256s93.31,208,208,208,208-93.31,208-208S370.69,48,256,48ZM205.78,164.82C218.45,151.39,236.28,144,256,144s37.39,7.44,50.11,20.94C319,178.62,325.27,197,323.79,216.76,320.83,256,290.43,288,256,288s-64.89-32-67.79-71.25C186.74,196.83,193,178.39,205.78,164.82ZM256,432a175.49,175.49,0,0,1-126-53.22,122.91,122.91,0,0,1,35.14-33.44C190.63,329,222.89,320,256,320s65.37,9,90.83,25.34A122.87,122.87,0,0,1,382,378.78,175.45,175.45,0,0,1,256,432Z"/></svg>Sign Up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:user_login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-o</title><path d="M192,176V136a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V376a40,40,0,0,1-40,40H240c-22.09,0-48-17.91-48-40V336" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><polyline points="288 336 368 256 288 176" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><line x1="80" y1="256" x2="352" y2="256" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/></svg>Log In</a>
            </li>
        {% else %}
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="navlink my-color" href="{% url 'basic:logout' %}">{{ request.user }} : Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:register' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-j</title><path style="fill:cornsilk;" d="M256,48C141.31,48,48,141.31,48,256s93.31,208,208,208,208-93.31,208-208S370.69,48,256,48ZM205.78,164.82C218.45,151.39,236.28,144,256,144s37.39,7.44,50.11,20.94C319,178.62,325.27,197,323.79,216.76,320.83,256,290.43,288,256,288s-64.89-32-67.79-71.25C186.74,196.83,193,178.39,205.78,164.82ZM256,432a175.49,175.49,0,0,1-126-53.22,122.91,122.91,0,0,1,35.14-33.44C190.63,329,222.89,320,256,320s65.37,9,90.83,25.34A122.87,122.87,0,0,1,382,378.78,175.45,175.45,0,0,1,256,432Z"/></svg>Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:user_login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-o</title><path d="M192,176V136a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V376a40,40,0,0,1-40,40H240c-22.09,0-48-17.91-48-40V336" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><polyline points="288 336 368 256 288 176" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><line x1="80" y1="256" x2="352" y2="256" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/></svg>Log In</a>
                </li>
            {% endif %}
        {% endif %}
    </ul>
</nav>

<body>

    {% block content %}



    {% endblock %}




    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

templates/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>OUR BLOGGING SITE</title>
    <link rel="stylesheet" href="{% static 'mycss/style.css' %}"/>
</head>
<nav class="navbar navbar-dark bg-dark">
    <ul class="nav justify-content-left">
        <li class="nav-item">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link my-color" href="{% url 'basic:procedure' %}">Procedure</a>
        </li>
        {% if user.is_superuser %}

            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">Members</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">To Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:display1' %}">My Profile</a>
            </li>

        {% else %}
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:post_topic_list' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:member_list' %}">Members</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:post_create' id=user %}">To Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:my_profile' %}">My Profile</a>
                </li>
            {% else %}

                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">Members</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">To Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:display1' %}">My Profile</a>
                </li>
            {% endif %}
        {% endif %}
    </ul>
    <ul class="nav justify-content-right">
        {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:register' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-j</title><path style="fill:cornsilk;" d="M256,48C141.31,48,48,141.31,48,256s93.31,208,208,208,208-93.31,208-208S370.69,48,256,48ZM205.78,164.82C218.45,151.39,236.28,144,256,144s37.39,7.44,50.11,20.94C319,178.62,325.27,197,323.79,216.76,320.83,256,290.43,288,256,288s-64.89-32-67.79-71.25C186.74,196.83,193,178.39,205.78,164.82ZM256,432a175.49,175.49,0,0,1-126-53.22,122.91,122.91,0,0,1,35.14-33.44C190.63,329,222.89,320,256,320s65.37,9,90.83,25.34A122.87,122.87,0,0,1,382,378.78,175.45,175.45,0,0,1,256,432Z"/></svg>Sign Up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link my-color" href="{% url 'basic:user_login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-o</title><path d="M192,176V136a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V376a40,40,0,0,1-40,40H240c-22.09,0-48-17.91-48-40V336" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><polyline points="288 336 368 256 288 176" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><line x1="80" y1="256" x2="352" y2="256" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/></svg>Log In</a>
            </li>
        {% else %}
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="navlink my-color" href="{% url 'basic:logout' %}">{{ request.user }} : Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:register' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-j</title><path style="fill:cornsilk;" d="M256,48C141.31,48,48,141.31,48,256s93.31,208,208,208,208-93.31,208-208S370.69,48,256,48ZM205.78,164.82C218.45,151.39,236.28,144,256,144s37.39,7.44,50.11,20.94C319,178.62,325.27,197,323.79,216.76,320.83,256,290.43,288,256,288s-64.89-32-67.79-71.25C186.74,196.83,193,178.39,205.78,164.82ZM256,432a175.49,175.49,0,0,1-126-53.22,122.91,122.91,0,0,1,35.14-33.44C190.63,329,222.89,320,256,320s65.37,9,90.83,25.34A122.87,122.87,0,0,1,382,378.78,175.45,175.45,0,0,1,256,432Z"/></svg>Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-color" href="{% url 'basic:user_login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 512 512"><title>ionicons-v5-o</title><path d="M192,176V136a40,40,0,0,1,40-40H392a40,40,0,0,1,40,40V376a40,40,0,0,1-40,40H240c-22.09,0-48-17.91-48-40V336" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><polyline points="288 336 368 256 288 176" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/><line x1="80" y1="256" x2="352" y2="256" style="fill:none;stroke:cornsilk;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"/></svg>Log In</a>
                </li>
            {% endif %}
        {% endif %}
    </ul>
</nav>

<body>

    {% block content %}



    {% endblock %}
    <h4>All the posts in this Blog are related to these :</h4>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static 'myimage/sc_tech.jpg' %}" height="500" width="50" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'myimage/sc_tech_1.jpg' %}" height="500" width="50" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'myimage/art_culture.jpg' %}" height="500" width="50" alt="Third slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'myimage/art_culture_1.jpg' %}" height="500" width="50" alt="Fourth slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'myimage/literature.jpg' %}" height="500" width="50" alt="Fifth slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static 'myimage/yoga.jpg' %}" height="500" width="50" alt="Sixth slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>




    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

templates/confirm_deletion.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <form action="{% url 'basic:delete' pk=user.id %}" method="POST">
                {% csrf_token %}
                <h3>Hey! {{ user.first_name }} {{ user.last_name }}</h3>
                <h3>Are you sure about deleting yourself from this Blog ?</h3>
                <button class="btn btn-primary" type="submit">Yes</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/display1.html
{% extends 'base1.html' %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <div class="alert alert-danger">
                <strong>Oops!</strong> If you're already a member, first LogIn else SignUp.
            </div>
        </div>
    </div>   
{% endblock %}

templates/index.html
{% extends 'base1.html' %}

{% block content %}
<div class="jumbotron vertical-center">
    <div class="container p-3 my-3 bg-primary text-white text-center">
        <h1>Welcome to your Blogging Site!</h1>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-4 text-center abc">
            <form action="{% url 'basic:user_login' %}" method="POST">
                {% csrf_token %}
                <p class="h4 mb-4 text-left">Login to continue</p>
                <p class="text-left">Signin to get connect to this Blogging Site.</p>
                {% if error %}
                    <ul>
                        <li style="color: red;">{{error}}</li>
                        <li style="color: red;">Please, click on LogIn page to try again.</li>
                    </ul> 
                {% endif %} 
                <label for="username" class="in">Username</label> 
                <input type="text" id="username" name="username" class="form-control mb-4" placeholder="Enter Username"><br> 
                <label for="password" class="in">Password</label> 
                <input type="password" id="password" name="password" class="form-control mb-4" placeholder="Enter Password">
                <div class="d-flex justify-content-center">
                    <!-- <div>
                        <!-- Remember me -->
                        <!-- <div class="custom-control custom-checkbox text-left"> <input type="checkbox" class="custom-control-input"> <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label> </div>
                    </div> --> 
                </div> 
                <!-- Sign in button --> 
                <button class="btn btn-info btn-block " type="submit" style="background-image: url(https://i.imgur.com/6YuRxJA.png)">LOGIN</button>
                <a href="{% url 'password_reset' %}">Forgot Password</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/my_profile.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>Your Details :</h1>
                {% if user %}
                    <ol>
                        <li><h3>Your User Id : {{ user.id }}</h3></li>
                        <li><h3>Your Firstname : {{ user.first_name }}</h3></li>
                        <li><h3>Your Lastname : {{ user.last_name }}</h3></li>
                        <li><h3>Your Username : {{ user }}</h3></li>
                        <li><h3>Your Email ID : {{ user.email }}</h3></li>
                        <li><h3>Your Profile Pic :</h3>
                            {% if user.userprofileinfo.profile_pic %}
                                <img src="{{ user.userprofileinfo.profile_pic.url }}" height="200">
                            {% else %}
                                <p>You haven't uploaded any profile picture yet.</p>
                            {% endif %}
                        </li>
                    </ol>  
                {% endif %}
            <form>
                {% csrf_token %}
                <div class="btn-group">
                    <button class="btn btn-warning" type="submit"><a href="{% url 'basic:userupdate' id=user.id %}" class="text-dark">Update</a></button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-secondary" type="submit"><a href="{% url 'basic:uploadpropic' pk=user.userprofileinfo.id %}" class="text-light">Update Profile Pic</a></button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-danger" type="submit"><a href="{% url 'basic:confirm_deletion' pk=user.id %}" class="text-white">Delete</a></button>
                </div>   
            </form>
        </div>
    </div>
{% endblock %}

templates/post_comment_no.html
{% extends 'base.html' %}
{% block content %}
    <div class="container text-align-center">
        <div class="jumbotron">
            <div class="main-comment-section">
                <p>{{ post.topic }}</p>
                <p>{{ post.date }}</p>
                <p> By<a href="{% url 'basic:view_profile' user=post.author %}"> {{ post.author|capfirst }}</p></a>
                <p>{{ post.content }}</p>
                <form class="form-group-row" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if post.video_clips %}
                        <video controls width='50%' height='40%'>
                            <source src="{{ post.video_clips.url }}">
                        </video>
                    {% endif %}
                    {% if post.images %}
                        <img src="{{ post.images.url }}" height="100">
                    {% endif %}
                    {% if post.site_url %}
                        Site: <a href="{{ post.site_url }}">{{ post.site_url }}</a>
                    {% endif %}
                </form>
                <div class="d-flex flex-lg-row justify-content-between">
                    
                    <a href="{% url 'basic:comment_view' id=post.id %}" >Total Comments = {{ comments.count }}</a>
                    {% if post.author != request.user %}
                        <a href="{% url 'basic:comment_create_view' id=post.id %}" class="btn btn-info btn-sm" role="button" aria-disabled="true">New Comment</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user_update.html
{% extends 'base.html' %}
{% block content %}
    
    <div class = 'container justify-content-center'>
        <div class="jumbotron">
            <form action="{% url 'basic:edit_user' id=user.id %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="Firstname" class="col-xs-2">Firstname</label>
                    <input type="text" class="col-xs-2" id="Firstname" name="firstname" style="width:300px" value="{{user.first_name}}"><br>
                    <label for="Lastname" class="col-xs-2">Lastname</label>
                    <input type="text" class="col-xs-2" id="Lastname" name="lastname" style="width:300px" value="{{user.last_name}}"><br>
                    <label for="InputEmail" class="col-xs-2">Email address</label>
                    <input type="email" class="col-xs-2" id="InputEmail" aria-describedby="emailHelp" style="width:300px" name="email" value="{{user.email}}">
                    <div class="btn-group">
                        <button type="submit" class="btn btn-primary text-center" style="color: burlywood;">Submit</button>
                    </div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-danger text-center"><a href="{% url 'basic:my_profile' %}" class="text-white">Cancel</a></button>
                    </div>
                </div>
                
            </form>
        </div>
    </div>
       
{% endblock %}